spring:
  application:
    name: order-processing-system
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: ${DB_USERNAME:MyUser}
    password: ${DB_PASSWORD:MyPass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mvc:
    problemdetails:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

app:
  kafka:
    topic:
      order-events: order-events